### ISSUE TITLE
Shouldn't we store q final as attribute for edges after vertical equilibrium?

### ISSUE THREAD

**Issue by ricardoavelino** [compas-dev/compas_tna#11]
In other contexts after the vertical equilibrium it may be useful to keep the qs that resulted in the required height.

attr['q'] = attr['f'] / form.edge_length(u,v)
or
attr['q'] = f[index, 0]

Is that any reason why we don't store the 'q's?

**Comment by tkmmark** [comment]
I totally agree! 
Also, I would also argue for storing the self-weight calculated by the LoadsUpdater (at the final step) as a vertex attribute.

By the way Ricardo... do you mean attr['q'] = q[index, 0]

**Comment by ricardoavelino** [comment]
This also @tkmmark

An enhancement could be actually to allow Loads3D(True/False) since for some problems the updates on the loads don't need to occur. And in any case I guess storing the information at the end of the calculation always will always be helpful...

**Comment by tkmmark** [comment]
Yes it is very useful... especially when we are doing post-TNA-vertical correction with FD, so that we could simply feed one form diagram output (from TNA) to the FD method.

**Comment by brgcode** [comment]
let me know if it is indeed fixed
